// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsMYaDe2mW-a7fmEed1tQPcE_wgWAyESg',
    appId: '1:554059473985:web:da1517c6ffb063f1a312c0',
    messagingSenderId: '554059473985',
    projectId: 'todoappfluttertask',
    authDomain: 'todoappfluttertask.firebaseapp.com',
    storageBucket: 'todoappfluttertask.appspot.com',
    measurementId: 'G-CV45TCQDD9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4yYZ288M8bnO7vv9sQsqH86xkTesI3xo',
    appId: '1:554059473985:android:5bf3d11c582bf462a312c0',
    messagingSenderId: '554059473985',
    projectId: 'todoappfluttertask',
    storageBucket: 'todoappfluttertask.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc7jY_KjPjaFgDlm5lov5sMGmUPegHwCY',
    appId: '1:554059473985:ios:e62d38a428566289a312c0',
    messagingSenderId: '554059473985',
    projectId: 'todoappfluttertask',
    storageBucket: 'todoappfluttertask.appspot.com',
    iosBundleId: 'com.example.todoappFlutterTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc7jY_KjPjaFgDlm5lov5sMGmUPegHwCY',
    appId: '1:554059473985:ios:e62d38a428566289a312c0',
    messagingSenderId: '554059473985',
    projectId: 'todoappfluttertask',
    storageBucket: 'todoappfluttertask.appspot.com',
    iosBundleId: 'com.example.todoappFlutterTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsMYaDe2mW-a7fmEed1tQPcE_wgWAyESg',
    appId: '1:554059473985:web:065588dd84e7103ca312c0',
    messagingSenderId: '554059473985',
    projectId: 'todoappfluttertask',
    authDomain: 'todoappfluttertask.firebaseapp.com',
    storageBucket: 'todoappfluttertask.appspot.com',
    measurementId: 'G-DYBEDLD8G4',
  );
}
